### ISSUE TITLE
fails to build with libfastjson 0.99.3

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/liblognorm#210]
liblognorm fails to build with libfastjson 0.99.3:

```
[   52s] enc_syslog.c:189:35: error: 'name' undeclared (first use in this function)
[   52s]   json_object_object_foreach(json, name, field) {
[   52s]                                    ^~~~
[   52s] enc_syslog.c:189:35: note: each undeclared identifier is reported only once for each function it appears in
[   52s] enc_syslog.c:189:41: error: 'field' undeclared (first use in this function)
[   52s]   json_object_object_foreach(json, name, field) {
[   52s]                                          ^~~~~
[   52s] enc_syslog.c:189:48: error: expected ';' before '{' token
[   52s]   json_object_object_foreach(json, name, field) {
[   52s]                                                 ^
```

**Comment by andreasstieger** [comment]
I guess this has been discussed on the ML already:
http://lists.adiscon.net/pipermail/rsyslog/2016-July/043051.html

**Comment by rgerhards** [comment]
This was a problem in libfastjson release, which has been fixed in the interim. Also, we updated the buildbot machines to libfastjson 0.99.3, and all works there well. So I think I can close the issue without risk.
